### ISSUE TITLE
ADD FAUCET LINK IN DOCS FOR THE DEVS

### ISSUE THREAD

**Issue by aeyshubh** [Phala-Network/phala-docs#26]
I can find Matic Faucet in the official docs, but not a single link of PHA Faucet, please add a link there.

**Comment by HashWarlock** [comment]
Official Faucet has not been announced. We will update docs when the faucet goes live.

**Comment by h4x3rotab** [comment]
You can get Test PHA from phat.phala.network already. Open it and switch to the PoC6 testnet. Then it shows a button to get testnet token.

**Comment by aeyshubh** [comment]
For now it would be good if "phat.phala.network" would be added into the docs under a faucet section , till official faucet is released.

**Comment by HashWarlock** [comment]
We have it here https://docs.phala.network/developers/getting-started/phat-contract-console#claim-test-tokens but you're right. This is not intuitive or easy to find. I'll break it out into a section on how to claim testnet PHA this week.

**Comment by aeyshubh** [comment]
https://phala.network/faucet , gg team
